/**
 * pg_service 1.0
 * pg_service
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package ru.data.models

import com.squareup.moshi.Json


/**
 * 
 * @param userRank position on user among best scores
 */
data class UserRankResponse (

    /* position on user among best scores */
    @Json(name = "user_rank") val userRank: kotlin.Int
) {
}
